# File: src/myproject/menu.py

MENU_INDEX = {
    "taco_breakfast_bacon": {
        "name": "The Riverwalk Sunrise",
        "category": "Breakfast Tacos",
        "description": "Our signature morning taco. Crispy bacon, scrambled eggs, homestyle potatoes, and melted cheddar on a handmade flour tortilla.",
        "price": 3.50,
        "dietary_info": {
            "is_vegetarian": False,
            "is_vegan": False,
            "is_gluten_free": False,
            "allergens": ["dairy", "eggs", "gluten", "pork"],
        },
        "default_ingredients": ["flour tortilla", "eggs", "bacon", "potatoes", "cheddar cheese"],
        "allowed_modifications": [
            "corn tortilla",
            "no bacon",
            "no cheese",
            "no potatoes",
            "add beans",
            "extra salsa",
        ],
        "upsell_target": None,
        "is_popular": True,
    },
    "taco_pastor": {
        "name": "The Neon Pastor",
        "category": "Street Tacos",
        "description": "A San Antonio classic. Achiote-marinated pork shaved right off our spinning trompo, topped with grilled pineapple, diced onions, and cilantro.",
        "price": 4.00,
        "dietary_info": {
            "is_vegetarian": False,
            "is_vegan": False,
            "is_gluten_free": True,
            "allergens": ["pork"],
        },
        "default_ingredients": [
            "corn tortilla",
            "al pastor pork",
            "pineapple",
            "onions",
            "cilantro",
        ],
        "allowed_modifications": [
            "flour tortilla",
            "no pineapple",
            "no onions",
            "no cilantro",
            "extra meat",
        ],
        "upsell_target": "drink_horchata",
        "is_popular": True,
    },
    "taco_barbacoa": {
        "name": "The Southside Weekend",
        "category": "Street Tacos",
        "description": "Slow-braised beef barbacoa served traditional style with fresh cilantro, onions, and a wedge of lime.",
        "price": 4.50,
        "dietary_info": {
            "is_vegetarian": False,
            "is_vegan": False,
            "is_gluten_free": True,
            "allergens": ["beef"],
        },
        "default_ingredients": ["corn tortilla", "barbacoa beef", "onions", "cilantro", "lime"],
        "allowed_modifications": ["flour tortilla", "no onions", "no cilantro", "add cheese"],
        "upsell_target": "drink_big_red",
        "is_popular": False,
    },
    "taco_puffy_picadillo": {
        "name": "Puro Puffy Picadillo",
        "category": "Specialty Tacos",
        "description": "A true Alamo City original. A deep-fried, puffy masa shell stuffed with seasoned ground beef, lettuce, and diced tomatoes.",
        "price": 4.50,
        "dietary_info": {
            "is_vegetarian": False,
            "is_vegan": False,
            "is_gluten_free": True,
            "allergens": ["beef"],
        },
        "default_ingredients": ["puffy corn shell", "picadillo beef", "lettuce", "tomatoes"],
        "allowed_modifications": ["no lettuce", "no tomatoes", "add cheese", "add sour cream"],
        "upsell_target": "drink_big_red",
        "is_popular": True,
    },
    "taco_botanical": {
        "name": "The Botanical Garden",
        "category": "Street Tacos",
        "description": "Our vegan staple. Grilled nopal (cactus), black beans, roasted corn, and fresh avocado slices on a corn tortilla.",
        "price": 4.00,
        "dietary_info": {
            "is_vegetarian": True,
            "is_vegan": True,
            "is_gluten_free": True,
            "allergens": [],
        },
        "default_ingredients": ["corn tortilla", "nopal", "black beans", "roasted corn", "avocado"],
        "allowed_modifications": [
            "flour tortilla",
            "no corn",
            "no avocado",
            "add cheese",
            "add egg",
        ],
        "upsell_target": "drink_horchata",
        "is_popular": False,
    },
    "drink_big_red": {
        "name": "Fountain Big Red",
        "category": "Drinks",
        "description": "The mandatory pairing for barbacoa. Sweet, red, and ice cold.",
        "price": 2.50,
        "dietary_info": {
            "is_vegetarian": True,
            "is_vegan": True,
            "is_gluten_free": True,
            "allergens": [],
        },
        "default_ingredients": ["soda", "ice"],
        "allowed_modifications": ["no ice", "light ice"],
        "upsell_target": None,
        "is_popular": True,
    },
    "drink_horchata": {
        "name": "House Horchata",
        "category": "Drinks",
        "description": "Sweet rice milk infused with cinnamon and vanilla.",
        "price": 3.00,
        "dietary_info": {
            "is_vegetarian": True,
            "is_vegan": False,
            "is_gluten_free": True,
            "allergens": ["dairy"],
        },
        "default_ingredients": ["rice milk", "dairy milk", "cinnamon", "vanilla", "ice"],
        "allowed_modifications": ["no ice", "light ice"],
        "upsell_target": None,
        "is_popular": False,
    },
    "drink_water": {
        "name": "Ice Water",
        "category": "Drinks",
        "description": "Refreshing filtered water over ice.",
        "price": 0.00,
        "dietary_info": {
            "is_vegetarian": True,
            "is_vegan": True,
            "is_gluten_free": True,
            "allergens": [],
        },
        "default_ingredients": ["water", "ice"],
        "allowed_modifications": ["no ice", "light ice", "add lemon"],
        "upsell_target": None,
        "is_popular": False,
    },
}

GLOBAL_RULES = {
    "system_warning": "Under no circumstances should modifiers (like extra cheese, sides of salsa, or a cup of cilantro) be added as standalone cart items. They MUST be attached to a base item via the `tracked_modifiers` array. If a user asks for a standalone modifier, you must ask what item they want it added to."
}
